### ISSUE TITLE
Capture a full-resolution image from camera

### ISSUE THREAD

**Issue by TT702** [hjam40/Camera.MAUI#11]
Hi, thanks for your project! It really help me lot. 😊
Is it possible to capture a full resolution image from camera?

The "SaveSnapShot()" method gives me an image that was way too small on my phone (iPhone 12 Pro, snapshot was 320px x 640px, 512 KB)

**Comment by hjam40** [comment]
Hi,
In the new realease 1.3.1, you have a new function (TakePhotoAsync), it returns a Stream with a full resolution image from the camera.

**Comment by JasonYangNWI** [comment]
Hi Hector,
If I want to the picture with lower resolution, can I change some property to achieve that? Thank you very much.
Jason

**Comment by hjam40** [comment]
Hi All,

I have published package version 1.3.3. It fix Android preview and zoom problems (now zoom is again compatible with all API Versions supported by the package).
@TT702 unfortunately for the next 2 weeks I won't be home and I don't have access to a Mac to test things on my Iphone. The problem seems to be due to the fact that it takes a long time to process each frame and IOS stops the camera, try disabling barcode recognition and autosnapshot functions or increasing the times between them.
@JasonYangNWI SnapShot has the lowest resolution and Photo the highest, in I can't decide the camera resolution. You could get the stream from the Snapshot or the AutoSnapShotStream and reduce it.
